version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: >
      bash -c "python manage.py test &&
               python manage.py migrate &&
               python manage.py loaddata user_data.json &&
               python manage.py loaddata ad_mediation_data.json &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8089:8089"
    depends_on:
      - db
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
