# Generated by Django 2.2.2 on 2019-06-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_mediation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='order',
            field=models.IntegerField(default=9999),
        ),
    ]
